/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardIndustriesRouteImport } from './routes/dashboard.industries'
import { Route as DashboardHrisRouteImport } from './routes/dashboard.hris'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardCrmRouteImport } from './routes/dashboard.crm'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAccountingRouteImport } from './routes/dashboard.accounting'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPendingRouteImport } from './routes/admin.pending'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIndustriesRoute = DashboardIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHrisRoute = DashboardHrisRouteImport.update({
  id: '/hris',
  path: '/hris',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingRoute = DashboardAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/hris': typeof DashboardHrisRoute
  '/dashboard/industries': typeof DashboardIndustriesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/hris': typeof DashboardHrisRoute
  '/dashboard/industries': typeof DashboardIndustriesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/hris': typeof DashboardHrisRoute
  '/dashboard/industries': typeof DashboardIndustriesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin/payments'
    | '/admin/pending'
    | '/admin/users'
    | '/dashboard/accounting'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/compliance'
    | '/dashboard/crm'
    | '/dashboard/documents'
    | '/dashboard/hris'
    | '/dashboard/industries'
    | '/dashboard/reports'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/admin/payments'
    | '/admin/pending'
    | '/admin/users'
    | '/dashboard/accounting'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/compliance'
    | '/dashboard/crm'
    | '/dashboard/documents'
    | '/dashboard/hris'
    | '/dashboard/industries'
    | '/dashboard/reports'
    | '/admin'
    | '/dashboard'
    | '/dashboard/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin/payments'
    | '/admin/pending'
    | '/admin/users'
    | '/dashboard/accounting'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/compliance'
    | '/dashboard/crm'
    | '/dashboard/documents'
    | '/dashboard/hris'
    | '/dashboard/industries'
    | '/dashboard/reports'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/industries': {
      id: '/dashboard/industries'
      path: '/industries'
      fullPath: '/dashboard/industries'
      preLoaderRoute: typeof DashboardIndustriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hris': {
      id: '/dashboard/hris'
      path: '/hris'
      fullPath: '/dashboard/hris'
      preLoaderRoute: typeof DashboardHrisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardHrisRoute: typeof DashboardHrisRoute
  DashboardIndustriesRoute: typeof DashboardIndustriesRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardHrisRoute: DashboardHrisRoute,
  DashboardIndustriesRoute: DashboardIndustriesRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
